### ISSUE TITLE
Width and height seem to be switched somewhere.

### ISSUE THREAD

**Issue by mblander** [nethuestechnologies/charts-nethues#1]
First of all thank you for your ChartJS package, it has been easy to implement.

I create a new chart  with the following code: 
`<nethues-charts type="line" height="400px" width="800px" [data]="data"></nethues-charts>`

The shown chart has the following dimensions: 800px height and 400px width.
The dimensions seem to been switched.

In the index.js line 96:
`[style.width]=\"height\" [style.height]=\"width\"`

**Comment by nethues** [comment]
Hi @mblander ,
Thanks for writing us. We have fixed the height and width issue in the version 1.0.1
